# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCommander < Formula
  desc "TUI application wrapping the AWS CLI for easy browsing and management of AWS resources."
  homepage "https://github.com/cmd-tools/aws-commander"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Darwin_x86_64.tar.gz"
      sha256 "3453af0d9dfe632c8a4e8a95fed24f17d94564ff6d278e7c8ba08034c2121e0d"

      def install
        bin.install "aws-commander"
      end
    end
    on_arm do
      url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Darwin_arm64.tar.gz"
      sha256 "c1bd152f795fa1a9ff4dea7372df5fff347de8ba5551f0d2b9d873ad9560499e"

      def install
        bin.install "aws-commander"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Linux_x86_64.tar.gz"
        sha256 "4b2eff5ba0e48a68837936f968f12fcd7c8d13fc0b870aa773d6003ffbb34b43"

        def install
          bin.install "aws-commander"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Linux_arm64.tar.gz"
        sha256 "a1f44baadc97d41bf93115b6bce3e0176d5329eb33b970af7bb7765f41cb8e5e"

        def install
          bin.install "aws-commander"
        end
      end
    end
  end
end
