# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCommander < Formula
  desc "TUI application wrapping the AWS CLI for easy browsing and management of AWS resources."
  homepage "https://github.com/cmd-tools/aws-commander"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Darwin_x86_64.tar.gz"
      sha256 "1aceb8afbb119bca69b47e24784a5ff90ea8570571342d8cd6b879e81097099e"

      def install
        bin.install "aws-commander"
      end
    end
    on_arm do
      url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Darwin_arm64.tar.gz"
      sha256 "20335c982f25459c816c6d4b2831d3bfe9b2abb0292f44e1ce74835e70e4e761"

      def install
        bin.install "aws-commander"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Linux_x86_64.tar.gz"
        sha256 "fc63d6ad296daba51dcdc5c8142d22f91193b0c4148fb323e786714149ead594"

        def install
          bin.install "aws-commander"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmd-tools/aws-commander/releases/download/0.0.1/aws-commander_Linux_arm64.tar.gz"
        sha256 "a02353ec9dcd305fdd1111dafdc257a5f02dc4e1e7ea603619662cd23c7f2582"

        def install
          bin.install "aws-commander"
        end
      end
    end
  end
end
