# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipv4mix < Formula
  desc "ipv4mix creates various mixed representations of a specified IPv4 address. It outputs the IP in different formats, including decimal, hexadecimal, octal, and their combinations, providing a versatile view of the address."
  homepage "https://github.com/cmd-tools/ipv4mix"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/cmd-tools/ipv4mix/releases/download/0.0.1/ipv4mix_Darwin_x86_64.tar.gz"
      sha256 "df670949f0322ae7753ed087eedcdfc53620c8d420c979b00d0f443fd7964e6b"

      def install
        bin.install "ipv4mix"
      end
    end
    on_arm do
      url "https://github.com/cmd-tools/ipv4mix/releases/download/0.0.1/ipv4mix_Darwin_arm64.tar.gz"
      sha256 "6ff1a0655ce91ca7d4461dce5c6d2bb1b6e67294ef3bc029d81a96a28efc4139"

      def install
        bin.install "ipv4mix"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmd-tools/ipv4mix/releases/download/0.0.1/ipv4mix_Linux_x86_64.tar.gz"
        sha256 "b5a07dc413f25a39efb27b5ecac8ed0fa22503b1415a8ca174f0f81f1cda3a79"

        def install
          bin.install "ipv4mix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmd-tools/ipv4mix/releases/download/0.0.1/ipv4mix_Linux_arm64.tar.gz"
        sha256 "08b5dc944035634b72835e9e361c10ad7ed250ca5aa634a9d09130ceb9a2ec42"

        def install
          bin.install "ipv4mix"
        end
      end
    end
  end
end
